source 'https://rubygems.org'

gem 'rails', '4.0.0'

gem 'pg'
gem 'thin'

gem 'sass-rails',   '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', :platforms => :ruby

gem 'uglifier', '>= 1.3.0'

gem 'protected_attributes'

gem 'jquery-rails'
gem 'newrelic_rpm'