development:
  adapter: postgresql
  encoding: unicode
  database: resonance_development
  pool: 5
  username: postgres
  password: thisisapasswordmotherfucker

production:
  adapter: postgresql
  encoding: unicode
  database: resonance_production
  pool: 5
  username: resonance
  password:
